//  THRRE IMPORTANT POINT TO REMEMBER WHILE CALCULATING TIME COPPLEXITY

//    TIME COMPLEXITY WERE CALCULATED IN    [ Big  O notaion   = O(10) or O(4)]

   // 1. WORST CASE SCENERIO

   // 2. AVOID CONSTANT
   /*
       AVOID CONSTANT

           ex -  if time complexity beocme very large number then we have to avoid the constant 
               if TC = O (4*10^89  + 8*10^89 + 8)
                       so in this if we do not add the 8 or add the 8 it do not maek any changes becasuse it is itself becomae very big number and 8 doeent mean lot much
   
    */
    
          
   // 3. 